FROM node:12-alpine

WORKDIR /cd-ui

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/main" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/community" >> /etc/apk/repositories

RUN set -x && apk add --update --no-cache git
RUN set -x && apk add --update --no-cache curl docker=17.05.0-r0

COPY . /cd-ui
RUN cd ./ui && npm install --unsafe-perm --loglevel=warn